#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spyder Editor

Restructered on Wed 10 Nov 2020 14:15

@author: Laurens Stoop - l.p.stoop@uu.nl
"""


#%%
# =============================================================================
# Dependencies
# =============================================================================


# Importing modules
import xarray as xr
import numpy as np
import datetime
import os.path

# File locations
path_source = '/media/DataStager1/temp/'
path_save = '/media/DataStager1/DataECMLPKDD21/'

# Select the years to run
years = np.array([
            '1950', '1951', '1952',
            '1953', '1954', '1955',
            '1956', '1957', '1958',
            '1959', '1960', '1961',
            '1962', '1963', '1964',
            '1965', '1966', '1967',
            '1968', '1969', '1970',
            '1971', '1972', '1973',
            '1974', '1975', '1976',
            '1977', '1978',
            '1979', '1980', '1981',
            '1982', '1983', '1984',
            '1985', '1986', '1987',
            '1988', '1989', '1990',
            '1991', '1992', '1993',
            '1994', '1995', '1996',
            '1997', '1998', '1999',
            '2000', '2001', '2002',
            '2003', '2004', '2005',
            '2006', '2007', '2008',
            '2009', '2010', '2011',
            '2012', '2013', '2014',
            '2015', '2016', '2017',
            '2018', '2019'
        ])



print('NOTIFY: Basic setup done, defining functions')
#%%
# =============================================================================
# Function definitions
# =============================================================================


# Run over the years
for year in years:
        
        # Define the file name
        file_source = path_source+'ERA5-EU_'+year+'.nc'
        file_save = path_save+'ERA5-EU_'+year+'.nc'
        

        # IF the file doesn't exist, apply the distribution
        if os.path.isfile(file_save) == False:
            
            # Tell us the file exist
            print('NOTIFY: Now starting work on applying distribution for year '+year+'!')
            
            # open the source file
            with xr.open_dataset(file_source) as ds:
                # Open a new dataset
                with xr.Dataset() as ds2:
                
                    
                    print('------ action (0/2): Apply the distributions')                        
                    # Now apply the distributions            
                    ds2['SPV'] = ds.SPV
                    ds2['WON'] = ds.WON
                    ds2['WOF'] = ds.WOF
                    
                    print('------ action (1/2): Force load the new file to do the calculations')
                    # Force load the file
                    ds2.load()

                    # Set the demand attributes
                    ds2.SPV.attrs.update(
                            units = 'MWh',
                            short_name = 'SPV',
                            long_name = 'SolarPhotoVoltaic',
                            distribution = 'The distribution of SPV comes from Zuijlen et al.',
                            method = 'Based on Bett and Thornton, 2016',
                            description = 'Hourly generation of solar panels')
                
                    # Set the demand attributes
                    ds2.WON.attrs.update(
                            units = 'MWh',
                            short_name = 'WON',
                            description = 'Hourly power generated by onshore wind turbines with hubheigh 98 meter',
                            method = 'Power curve adapted based on expert feedback',
                            distribution = 'The distribution of SPV comes from van Zuijlen et al. 2019',
                            long_name = 'WindONshore')
                    
                    # Set the demand attributes
                    ds2.WOF.attrs.update(
                            units = 'MWh',
                            short_name = 'WOF',
                            description = 'Hourly power generated by offshore wind turbines with hubheigh 122 meter',
                            method = 'Power curve adapted based on expert feedback',
                            distribution = 'The distribution of SPV comes from van Zuijlen et al. 2019',
                            long_name = 'WindOFfshore')
                    
                    # attempt to use less data - This keeps precision as data was float 32
                    ds2['SPV'] = ds2.SPV.astype('float32')
                    ds2['WON'] = ds2.WON.astype('float32')
                    ds2['WOF'] = ds2.WOF.astype('float32')
                    
    
                    print('------ action (2/2): Save the file')
                    # Now save the file
                    #compression = 'zlib' # zlib is very smoll data
                    ds2.to_netcdf(file_save, format='NETCDF4', engine='netcdf4') # ,encoding={'SPV':{compression:True},'WON':{compression:True},'WOF':{compression:True}})
            
            
            
  